/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank.management;

import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import javax.swing.table.*;
import javax.swing.SwingConstants;

/**
 *
 * @author Ashish Bansal
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new Dimension(1360,725));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        p_upper = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_name11 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        b_logout = new javax.swing.JButton();
        b_accounts = new javax.swing.JButton();
        b_funds = new javax.swing.JButton();
        b_about = new javax.swing.JButton();
        l_update_contact_details = new javax.swing.JLabel();
        l_change_password = new javax.swing.JLabel();
        l_name1 = new javax.swing.JLabel();
        l_name12 = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        p_main_accounts = new javax.swing.JPanel();
        lm1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l_account_type = new javax.swing.JLabel();
        lm3 = new javax.swing.JLabel();
        l_total_amount = new javax.swing.JLabel();
        lm5 = new javax.swing.JLabel();
        lm7 = new javax.swing.JLabel();
        lm8 = new javax.swing.JLabel();
        b_summary = new javax.swing.JButton();
        l_account_id = new javax.swing.JLabel();
        l_holder_name = new javax.swing.JLabel();
        l_holder_balance = new javax.swing.JLabel();
        p_main_funds = new javax.swing.JPanel();
        l_funds_heading = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l_f_transaction_id = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_f_account_id = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        l_f_holder_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        l_f_balance = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        l_f_date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        transfer_submit = new javax.swing.JButton();
        p_main_change_password = new javax.swing.JPanel();
        l_c_1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        l_c_2 = new javax.swing.JLabel();
        l_user_id = new javax.swing.JLabel();
        l_c_01 = new javax.swing.JLabel();
        tf_old_password = new javax.swing.JTextField();
        l_c_02 = new javax.swing.JLabel();
        tf_new_password = new javax.swing.JTextField();
        l_c_03 = new javax.swing.JLabel();
        tf_new_password1 = new javax.swing.JTextField();
        b_change_password = new javax.swing.JButton();
        p_main_update = new javax.swing.JPanel();
        l_u_1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        l_u_01 = new javax.swing.JLabel();
        tf_u_name = new javax.swing.JTextField();
        l_u_11 = new javax.swing.JLabel();
        tf_u_birth = new javax.swing.JTextField();
        l_u_12 = new javax.swing.JLabel();
        tf_u_gender = new javax.swing.JTextField();
        l_u_02 = new javax.swing.JLabel();
        tf_u_contact = new javax.swing.JTextField();
        l_u_3 = new javax.swing.JLabel();
        tf_u_email = new javax.swing.JTextField();
        l_u_4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_u_address = new javax.swing.JTextArea();
        b_update = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        p_main_details = new javax.swing.JPanel();
        l_d_2 = new javax.swing.JLabel();
        l_d_6 = new javax.swing.JLabel();
        l_d_name = new javax.swing.JLabel();
        l_d_5 = new javax.swing.JLabel();
        l_d_birth = new javax.swing.JLabel();
        l_d_9 = new javax.swing.JLabel();
        l_d_gender = new javax.swing.JLabel();
        l_d_10 = new javax.swing.JLabel();
        l_d_contact = new javax.swing.JLabel();
        l_d_8 = new javax.swing.JLabel();
        l_d_email = new javax.swing.JLabel();
        l_d_7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_address = new javax.swing.JTextArea();
        b_update1 = new javax.swing.JButton();
        p_main_about = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p_main_account_summary = new javax.swing.JPanel();
        lm2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_account_summary = new javax.swing.JTable();
        p_side = new javax.swing.JPanel();
        p_side_accounts = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        b_user_details = new javax.swing.JButton();
        b_account_summary = new javax.swing.JButton();
        p_side_funds = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        b_user_details1 = new javax.swing.JButton();
        b_user_details2 = new javax.swing.JButton();
        p_side_about = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        p_side_update_details = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        p_side_change_password = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logged In");

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_upper.setLayout(null);

        l1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        l1.setText("BANK");
        p_upper.add(l1);
        l1.setBounds(60, 10, 60, 30);

        l_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p_upper.add(l_name);
        l_name.setBounds(290, 10, 200, 20);

        l_name11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_name11.setText("WELCOME");
        p_upper.add(l_name11);
        l_name11.setBounds(200, 10, 80, 20);

        l3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        l3.setText("NETBANKING");
        p_upper.add(l3);
        l3.setBounds(30, 40, 130, 30);

        b_logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_logout.setText("Logout");
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });
        p_upper.add(b_logout);
        b_logout.setBounds(1240, 10, 100, 30);

        b_accounts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_accounts.setText("Accounts");
        b_accounts.setFocusPainted(false);
        b_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_accountsActionPerformed(evt);
            }
        });
        p_upper.add(b_accounts);
        b_accounts.setBounds(190, 50, 110, 40);

        b_funds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_funds.setText("Funds Transfer");
        b_funds.setFocusPainted(false);
        b_funds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fundsActionPerformed(evt);
            }
        });
        p_upper.add(b_funds);
        b_funds.setBounds(300, 50, 150, 40);

        b_about.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_about.setText("About");
        b_about.setFocusPainted(false);
        b_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aboutActionPerformed(evt);
            }
        });
        p_upper.add(b_about);
        b_about.setBounds(450, 50, 90, 40);

        l_update_contact_details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_update_contact_details.setText("Update Contact Details");
        l_update_contact_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_update_contact_detailsMouseClicked(evt);
            }
        });
        p_upper.add(l_update_contact_details);
        l_update_contact_details.setBounds(1080, 20, 150, 17);

        l_change_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_change_password.setText("Change Password");
        l_change_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_change_passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_change_passwordMouseEntered(evt);
            }
        });
        p_upper.add(l_change_password);
        l_change_password.setBounds(950, 20, 120, 17);

        l_name1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p_upper.add(l_name1);
        l_name1.setBounds(290, 30, 200, 20);

        l_name12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l_name12.setText("ACCOUNT ID");
        p_upper.add(l_name12);
        l_name12.setBounds(200, 30, 90, 20);

        p1.add(p_upper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -1, 1350, 90));

        p_main.setBackground(new java.awt.Color(255, 255, 255));
        p_main.setLayout(new java.awt.CardLayout());

        p_main_accounts.setBackground(new java.awt.Color(255, 255, 255));

        lm1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lm1.setText("Account Summary");

        l_account_type.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_account_type.setText("Account Type");

        lm3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lm3.setText("Total Available Balance : INR");

        l_total_amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_total_amount.setText("Amount");

        lm5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lm5.setText("Account ID");

        lm7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lm7.setText("Name");

        lm8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lm8.setText("Available Balance");

        b_summary.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        b_summary.setText("View Account Summary");
        b_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_summaryActionPerformed(evt);
            }
        });

        l_account_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_account_id.setText("Account ID");

        l_holder_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_holder_name.setText("Name");

        l_holder_balance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        l_holder_balance.setText("Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_account_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lm3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lm5)
                            .addComponent(l_account_id))
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lm7)
                            .addComponent(l_holder_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lm8)
                            .addComponent(l_holder_balance))
                        .addGap(198, 198, 198)
                        .addComponent(b_summary)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_account_type)
                    .addComponent(lm3)
                    .addComponent(l_total_amount))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lm5)
                            .addComponent(lm7)
                            .addComponent(lm8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_account_id)
                            .addComponent(l_holder_name)
                            .addComponent(l_holder_balance)))
                    .addComponent(b_summary, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_main_accountsLayout = new javax.swing.GroupLayout(p_main_accounts);
        p_main_accounts.setLayout(p_main_accountsLayout);
        p_main_accountsLayout.setHorizontalGroup(
            p_main_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_accountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_accountsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lm1)
                .addGap(470, 470, 470))
        );
        p_main_accountsLayout.setVerticalGroup(
            p_main_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_accountsLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(lm1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        p_main.add(p_main_accounts, "card2");

        p_main_funds.setBackground(new java.awt.Color(255, 255, 255));

        l_funds_heading.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        l_funds_heading.setText("WITHDRAW MONEY");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("TRANSACTION ID");

        l_f_transaction_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("ACCOUNT ID");

        l_f_account_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("CUSTOMER NAME");

        l_f_holder_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("BALANCE");

        l_f_balance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("TRANSACTION DATE");

        l_f_date.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("AMOUNT");

        tf_amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        transfer_submit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        transfer_submit.setText("WITHDRAW");
        transfer_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_main_fundsLayout = new javax.swing.GroupLayout(p_main_funds);
        p_main_funds.setLayout(p_main_fundsLayout);
        p_main_fundsLayout.setHorizontalGroup(
            p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_fundsLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_fundsLayout.createSequentialGroup()
                        .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(351, 351, 351)
                        .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(l_f_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(l_f_account_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(l_f_holder_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_f_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_f_transaction_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_fundsLayout.createSequentialGroup()
                        .addComponent(transfer_submit)
                        .addGap(517, 517, 517))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_fundsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_funds_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
        );
        p_main_fundsLayout.setVerticalGroup(
            p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_fundsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(l_funds_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_main_fundsLayout.createSequentialGroup()
                        .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_main_fundsLayout.createSequentialGroup()
                                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_f_transaction_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8))
                            .addComponent(l_f_account_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10))
                    .addComponent(l_f_holder_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(l_f_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(l_f_date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(p_main_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(transfer_submit)
                .addGap(51, 51, 51))
        );

        p_main.add(p_main_funds, "card3");

        p_main_change_password.setBackground(new java.awt.Color(255, 255, 255));

        l_c_1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        l_c_1.setText("CHANGE PASSWORD");

        l_c_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_c_2.setText("USER ID");

        l_user_id.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        l_c_01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_c_01.setText("OLD PASSWORD");

        tf_old_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_c_02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_c_02.setText("NEW PASSWORD");

        tf_new_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_c_03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_c_03.setText("RE-ENTER NEW PASSWORD");

        tf_new_password1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        b_change_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_change_password.setText("SUBMIT");
        b_change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_change_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_change_password)
                .addGap(398, 398, 398))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_c_01)
                    .addComponent(l_c_02)
                    .addComponent(l_c_03)
                    .addComponent(l_c_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_old_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_new_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_new_password1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_user_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_user_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_c_2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_c_01)
                    .addComponent(tf_old_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_c_02)
                    .addComponent(tf_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_c_03)
                    .addComponent(tf_new_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(b_change_password)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout p_main_change_passwordLayout = new javax.swing.GroupLayout(p_main_change_password);
        p_main_change_password.setLayout(p_main_change_passwordLayout);
        p_main_change_passwordLayout.setHorizontalGroup(
            p_main_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_change_passwordLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_change_passwordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_c_1)
                .addGap(475, 475, 475))
        );
        p_main_change_passwordLayout.setVerticalGroup(
            p_main_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_change_passwordLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(l_c_1)
                .addGap(64, 64, 64)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        p_main.add(p_main_change_password, "card7");

        p_main_update.setBackground(new java.awt.Color(255, 255, 255));

        l_u_1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        l_u_1.setText("UPDATE DETAILS");

        l_u_01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_01.setText("NAME");

        tf_u_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_u_11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_11.setText("BIRTH DATE");

        tf_u_birth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_u_birth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_u_birthKeyTyped(evt);
            }
        });

        l_u_12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_12.setText("GENDER");

        tf_u_gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_u_02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_02.setText("CONTACT NUMBER");

        tf_u_contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_u_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_u_contactKeyTyped(evt);
            }
        });

        l_u_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_3.setText("EMAIL");

        tf_u_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_u_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_u_4.setText("ADDRESS");

        ta_u_address.setColumns(20);
        ta_u_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ta_u_address.setRows(5);
        jScrollPane1.setViewportView(ta_u_address);

        b_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_update.setText("SUBMIT");
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("(yyyy/mm/dd)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_u_4)
                                    .addComponent(l_u_3))
                                .addGap(246, 246, 246)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_u_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(l_u_12)
                                .addGap(246, 246, 246)
                                .addComponent(tf_u_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(l_u_02)
                                .addGap(246, 246, 246)
                                .addComponent(tf_u_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(l_u_01)
                                        .addComponent(l_u_11))
                                    .addGap(246, 246, 246)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_u_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_u_birth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(b_update)
                        .addGap(475, 475, 475))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_u_01)
                    .addComponent(tf_u_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_u_11)
                    .addComponent(tf_u_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_u_12)
                    .addComponent(tf_u_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_u_02)
                    .addComponent(tf_u_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_u_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_u_3))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_u_4))
                .addGap(18, 18, 18)
                .addComponent(b_update)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout p_main_updateLayout = new javax.swing.GroupLayout(p_main_update);
        p_main_update.setLayout(p_main_updateLayout);
        p_main_updateLayout.setHorizontalGroup(
            p_main_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_u_1)
                .addGap(483, 483, 483))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_main_updateLayout.setVerticalGroup(
            p_main_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_updateLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(l_u_1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        p_main.add(p_main_update, "card2");

        p_main_details.setBackground(new java.awt.Color(255, 255, 255));

        l_d_2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        l_d_2.setText("DETAILS");

        l_d_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_6.setText("NAME");

        l_d_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_d_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_5.setText("BIRTH DATE");

        l_d_birth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_d_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_9.setText("GENDER");

        l_d_gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_d_10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_10.setText("CONTACT NUMBER");

        l_d_contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_d_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_8.setText("EMAIL");

        l_d_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        l_d_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l_d_7.setText("ADDRESS");

        ta_address.setColumns(20);
        ta_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ta_address.setRows(5);
        jScrollPane2.setViewportView(ta_address);

        b_update1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_update1.setText("UPDATE DETAILS");
        b_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_main_detailsLayout = new javax.swing.GroupLayout(p_main_details);
        p_main_details.setLayout(p_main_detailsLayout);
        p_main_detailsLayout.setHorizontalGroup(
            p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_detailsLayout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(b_update1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_detailsLayout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_d_7)
                    .addComponent(l_d_8)
                    .addComponent(l_d_6)
                    .addComponent(l_d_5)
                    .addComponent(l_d_9)
                    .addComponent(l_d_10))
                .addGap(250, 250, 250)
                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(l_d_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_d_birth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_d_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_d_contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_d_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(275, 275, 275))
            .addGroup(p_main_detailsLayout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(l_d_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_main_detailsLayout.setVerticalGroup(
            p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_detailsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(l_d_2)
                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_main_detailsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_main_detailsLayout.createSequentialGroup()
                                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(p_main_detailsLayout.createSequentialGroup()
                                        .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(p_main_detailsLayout.createSequentialGroup()
                                                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(l_d_6)
                                                    .addComponent(l_d_name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36)
                                                .addComponent(l_d_5))
                                            .addComponent(l_d_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(l_d_9))
                                    .addComponent(l_d_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(l_d_10))
                            .addComponent(l_d_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(l_d_8))
                    .addGroup(p_main_detailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_d_email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(p_main_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_d_7))
                .addGap(38, 38, 38)
                .addComponent(b_update1)
                .addGap(28, 28, 28))
        );

        p_main.add(p_main_details, "card8");

        p_main_about.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jLabel2.setText("DEVELOPED BY:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("ASHISH BANSAL");

        javax.swing.GroupLayout p_main_aboutLayout = new javax.swing.GroupLayout(p_main_about);
        p_main_about.setLayout(p_main_aboutLayout);
        p_main_aboutLayout.setHorizontalGroup(
            p_main_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_aboutLayout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addGroup(p_main_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_aboutLayout.createSequentialGroup()
                        .addGroup(p_main_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(449, 449, 449))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main_aboutLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(417, 417, 417))))
        );
        p_main_aboutLayout.setVerticalGroup(
            p_main_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_aboutLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        p_main.add(p_main_about, "card4");

        p_main_account_summary.setBackground(new java.awt.Color(255, 255, 255));

        lm2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lm2.setText("Account Summary");

        table_account_summary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_account_summary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction_id", "Account_id", "Amount", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_account_summary);

        javax.swing.GroupLayout p_main_account_summaryLayout = new javax.swing.GroupLayout(p_main_account_summary);
        p_main_account_summary.setLayout(p_main_account_summaryLayout);
        p_main_account_summaryLayout.setHorizontalGroup(
            p_main_account_summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_account_summaryLayout.createSequentialGroup()
                .addGroup(p_main_account_summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_main_account_summaryLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(lm2))
                    .addGroup(p_main_account_summaryLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        p_main_account_summaryLayout.setVerticalGroup(
            p_main_account_summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main_account_summaryLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lm2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        p_main.add(p_main_account_summary, "card7");

        p1.add(p_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 90, 1230, 660));

        p_side.setLayout(new java.awt.CardLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("   Accounts");
        jLabel4.setOpaque(true);

        b_user_details.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_user_details.setText("User Details");
        b_user_details.setFocusPainted(false);
        b_user_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_user_detailsActionPerformed(evt);
            }
        });

        b_account_summary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_account_summary.setText("Account Summary");
        b_account_summary.setFocusPainted(false);
        b_account_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_account_summaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_side_accountsLayout = new javax.swing.GroupLayout(p_side_accounts);
        p_side_accounts.setLayout(p_side_accountsLayout);
        p_side_accountsLayout.setHorizontalGroup(
            p_side_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_user_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_account_summary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        p_side_accountsLayout.setVerticalGroup(
            p_side_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_side_accountsLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_user_details, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_account_summary, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 492, Short.MAX_VALUE))
        );

        p_side.add(p_side_accounts, "card2");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("   Funds Transfer");
        jLabel5.setOpaque(true);

        b_user_details1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_user_details1.setText("Deposite");
        b_user_details1.setFocusPainted(false);
        b_user_details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_user_details1ActionPerformed(evt);
            }
        });

        b_user_details2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_user_details2.setText("Withdraw");
        b_user_details2.setFocusPainted(false);
        b_user_details2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_user_details2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_side_fundsLayout = new javax.swing.GroupLayout(p_side_funds);
        p_side_funds.setLayout(p_side_fundsLayout);
        p_side_fundsLayout.setHorizontalGroup(
            p_side_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(b_user_details1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_user_details2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_side_fundsLayout.setVerticalGroup(
            p_side_fundsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_side_fundsLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_user_details1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_user_details2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 487, Short.MAX_VALUE))
        );

        p_side.add(p_side_funds, "card3");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("   About");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout p_side_aboutLayout = new javax.swing.GroupLayout(p_side_about);
        p_side_about.setLayout(p_side_aboutLayout);
        p_side_aboutLayout.setHorizontalGroup(
            p_side_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_side_aboutLayout.setVerticalGroup(
            p_side_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_side_aboutLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 574, Short.MAX_VALUE))
        );

        p_side.add(p_side_about, "card4");

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("   Update Details");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout p_side_update_detailsLayout = new javax.swing.GroupLayout(p_side_update_details);
        p_side_update_details.setLayout(p_side_update_detailsLayout);
        p_side_update_detailsLayout.setHorizontalGroup(
            p_side_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_side_update_detailsLayout.setVerticalGroup(
            p_side_update_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_side_update_detailsLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 574, Short.MAX_VALUE))
        );

        p_side.add(p_side_update_details, "card4");

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("   Change Password");
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout p_side_change_passwordLayout = new javax.swing.GroupLayout(p_side_change_password);
        p_side_change_password.setLayout(p_side_change_passwordLayout);
        p_side_change_passwordLayout.setHorizontalGroup(
            p_side_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_side_change_passwordLayout.setVerticalGroup(
            p_side_change_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_side_change_passwordLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 574, Short.MAX_VALUE))
        );

        p_side.add(p_side_change_password, "card4");

        p1.add(p_side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void set(String s,String account_id){
        l_name.setText(s.toUpperCase());
        l_name1.setText(account_id);
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            l_account_id.setText(rs.getString(1));
            l_holder_name.setText(rs.getString(2));
            l_holder_balance.setText(rs.getString(11));
            l_total_amount.setText(rs.getString(11));
            l_account_type.setText(rs.getString(6).substring(0,1).toUpperCase()+rs.getString(6)+"Account");
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    private void update_table()
    {
        try
        {            
            JTableHeader theader=table_account_summary.getTableHeader();
            theader.setFont(new Font("Tahoma",Font.PLAIN,14));
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String sql="select transaction_id as TRANSACTION_ID,transaction_type AS TRANSACTION_TYPE,transaction_date_time as DATE_TIME,amount as AMOUNT,balance as BALANCE from makes_transaction where account_id=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1, l_name1.getText());
            ResultSet rs=ps.executeQuery();
            table_account_summary.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }       
    }
    
    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        // TODO add your handling code here:

        Exit e=new Exit();
        dispose();
        e.show();
    }//GEN-LAST:event_b_logoutActionPerformed

    private void b_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_accountsActionPerformed
        // TODO add your handling code here:
        
        setAccounts();
        
    }//GEN-LAST:event_b_accountsActionPerformed

    private void b_fundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fundsActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_funds);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_funds);
        p_main.repaint();
        p_main.revalidate();   

        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            String count="Select count(transaction_id) from makes_transaction";
            PreparedStatement ps=con.prepareStatement(query);
            PreparedStatement ps2=con.prepareStatement(count);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            ResultSet rs2=ps2.executeQuery();
            rs.next();
            rs2.next();
            int count_entries=Integer.parseInt(rs2.getString(1));
            int entries=count_entries+1;
            l_f_transaction_id.setText(Integer.toString(entries));
            l_f_account_id.setText(rs.getString(1));
            l_f_holder_name.setText(rs.getString(2));
            l_f_balance.setText(rs.getString(11));
            l_f_date.setText(java.time.LocalDate.now().toString());
            tf_amount.setText("0.00");
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_b_fundsActionPerformed

    private void b_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aboutActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_about);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_about);
        p_main.repaint();
        p_main.revalidate();
        
    }//GEN-LAST:event_b_aboutActionPerformed

    private void l_change_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_change_passwordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_l_change_passwordMouseEntered

    private void l_change_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_change_passwordMouseClicked
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_change_password);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_change_password);
        p_main.repaint();
        p_main.revalidate();
        
        String account_id=l_name1.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            l_user_id.setText(rs.getString(5));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_l_change_passwordMouseClicked

    private void l_update_contact_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_update_contact_detailsMouseClicked
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_update_details);
        p_side.repaint();
        p_side.revalidate();
        
        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            tf_u_name.setText(rs.getString(2));
            tf_u_birth.setText(rs.getString(3));
            tf_u_gender.setText(rs.getString(4));
            tf_u_contact.setText(rs.getString(7));
            tf_u_email.setText(rs.getString(8));
            ta_u_address.setText(rs.getString(9));
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        p_main.removeAll();
        p_main.add(p_main_update);
        p_main.repaint();
        p_main.revalidate();
        
    }//GEN-LAST:event_l_update_contact_detailsMouseClicked

    private void b_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_summaryActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_accounts);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_account_summary);
        p_main.repaint();
        p_main.revalidate();
        
        update_table();
    }//GEN-LAST:event_b_summaryActionPerformed

    private void b_user_details1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_user_details1ActionPerformed
        // TODO add your handling code here:
        
        l_funds_heading.setText("DEPOSITE MONEY");
        transfer_submit.setText("DEPOSITE");
        
    }//GEN-LAST:event_b_user_details1ActionPerformed

    private void b_user_details2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_user_details2ActionPerformed
        // TODO add your handling code here:
        
        l_funds_heading.setText("WITHDRAW MONEY");
        transfer_submit.setText("WITHDRAW");
        
    }//GEN-LAST:event_b_user_details2ActionPerformed

    private void b_account_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_account_summaryActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_accounts);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_account_summary);
        p_main.repaint();
        p_main.revalidate();

        update_table();
    }//GEN-LAST:event_b_account_summaryActionPerformed

    private void b_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_update1ActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        
        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            tf_u_name.setText(rs.getString(2));
            tf_u_birth.setText(rs.getString(3));
            tf_u_gender.setText(rs.getString(4));
            tf_u_contact.setText(rs.getString(7));
            tf_u_email.setText(rs.getString(8));
            ta_u_address.setText(rs.getString(9));
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        p_main.removeAll();
        p_main.add(p_main_update);
        p_main.repaint();
        p_main.revalidate();
        
        
    }//GEN-LAST:event_b_update1ActionPerformed

    private void b_user_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_user_detailsActionPerformed
        // TODO add your handling code here:
        
        p_side.removeAll();
        p_side.add(p_side_accounts);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_details);
        p_main.repaint();
        p_main.revalidate();

        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            l_d_name.setText(rs.getString(2));
            l_d_birth.setText(rs.getString(3));
            l_d_gender.setText(rs.getString(4));
            l_d_contact.setText(rs.getString(7));
            l_d_email.setText(rs.getString(8));
            ta_address.setText(rs.getString(9));
            ta_address.setEditable(false);
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_b_user_detailsActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        
        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="update account set holder_name=?, birth_date=?, gender=?, contact_number=?, email_id=?, address=? where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, tf_u_name.getText());
            ps.setString(2, tf_u_birth.getText());
            ps.setString(3, tf_u_gender.getText());
            ps.setString(4, tf_u_contact.getText());
            ps.setString(5, tf_u_email.getText());
            ps.setString(6, ta_u_address.getText());
            ps.setString(7, account_id);
            int n=ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Details Successfully");
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        
        p_side.removeAll();
        p_side.add(p_side_accounts);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_accounts);
        p_main.repaint();
        p_main.revalidate();
        
        
    }//GEN-LAST:event_b_updateActionPerformed

    private void transfer_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_submitActionPerformed
        // TODO add your handling code here:
        if(l_funds_heading.getText().equals("WITHDRAW MONEY"))
        {
            Double left=Double.parseDouble(l_f_balance.getText())-Double.parseDouble(tf_amount.getText());
            if(left<0)
            {
                JOptionPane.showMessageDialog(null, "Withdraw amount greater than the account balance");
            }
            else if(left==Double.parseDouble(l_f_balance.getText()))
            {
                JOptionPane.showMessageDialog(null, "Please Enter an amount");
            }
            else
            {
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
                    String query="update account set balance=? where account_id=?";
                    PreparedStatement ps=con.prepareStatement(query);
                    ps.setString(1, left.toString());
                    ps.setString(2, l_name1.getText());
                    int success=ps.executeUpdate();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                makeTransaction(left,"withdraw");
                JOptionPane.showMessageDialog(null, "Transaction Successful");
                setAccounts();
            }
        }
        else
        {
            Double balance=Double.parseDouble(l_f_balance.getText())+Double.parseDouble(tf_amount.getText());
            if(balance==Double.parseDouble(l_f_balance.getText()))
            {
                JOptionPane.showMessageDialog(null, "Please Enter an amount");
            }
            else
            {
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
                    String query="update account set balance=? where account_id=?";
                    PreparedStatement ps=con.prepareStatement(query);
                    ps.setString(1, balance.toString());
                    ps.setString(2, l_name1.getText());
                    int success=ps.executeUpdate();
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
                makeTransaction(balance,"deposite");
                JOptionPane.showMessageDialog(null, "Transaction Successful");
                setAccounts();
            }
            
        }
    }//GEN-LAST:event_transfer_submitActionPerformed

    private void b_change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_change_passwordActionPerformed
        // TODO add your handling code here:
        
        if(tf_new_password.getText().equals(tf_new_password1.getText()))
        {
            String account_id=l_name1.getText();
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
                String query="Select * from account where account_id=?";
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1, account_id);
                ResultSet rs=ps.executeQuery();
                rs.next();
                String s1="Select * from user where user_id=?";
                PreparedStatement ps2=con.prepareStatement(s1);
                ps2.setString(1,rs.getString(5));
                ResultSet rs2=ps2.executeQuery();
                rs2.next();
                if(rs2.getString(3).equals(tf_old_password.getText()))
                {
                    String s2="update user set password=? where user_id=?";
                    PreparedStatement ps3=con.prepareStatement(s2);
                    ps3.setString(1,tf_new_password.getText());
                    ps3.setString(2,l_user_id.getText());
                    int update=ps3.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Password Changed!");
                    setAccounts();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Incorrect Old Password");
                }
            }
        
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "New Password and Re-entered Password Mismatch");
        }
    }//GEN-LAST:event_b_change_passwordActionPerformed

    private void tf_u_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_u_contactKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        int length=tf_u_contact.getText().length();
        if(!(Character.isDigit(c))) 
        {
            evt.consume();
        }
        else if(length>9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tf_u_contactKeyTyped

    private void tf_u_birthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_u_birthKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        int length=tf_u_birth.getText().length();
        if(length==4 | length==7)
        {
            if(!(c==KeyEvent.VK_BACK_SPACE | c==KeyEvent.VK_DELETE))
            {
                evt.setKeyChar('-');
            }            
        }
        else{
            if(!(Character.isDigit(c))) 
            {
                evt.consume();
            }
            else if(length>9)
            {
                evt.consume();
            }
        }
    }//GEN-LAST:event_tf_u_birthKeyTyped
    
    public void makeTransaction(Double i,String s)
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String s1="insert into makes_transaction values(?,?,current_timestamp(),?,?,?)";
            PreparedStatement ps2=con.prepareStatement(s1);
            ps2.setString(1, l_f_transaction_id.getText());
            ps2.setString(2, l_name1.getText());
            ps2.setString(3, tf_amount.getText());
            ps2.setString(4, Double.toString(i));
            ps2.setString(5, s);
            int a=ps2.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
    public void setAccounts()
    {
        p_side.removeAll();
        p_side.add(p_side_accounts);
        p_side.repaint();
        p_side.revalidate();
        
        p_main.removeAll();
        p_main.add(p_main_accounts);
        p_main.repaint();
        p_main.revalidate();
        
        String account_id=l_name1.getText();
        try{    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///bank_management","root","root");
            String query="Select * from account where account_id=?";
            PreparedStatement ps=con.prepareStatement(query);
            ps.setString(1, account_id);
            ResultSet rs=ps.executeQuery();
            rs.next();
            l_account_id.setText(rs.getString(1));
            l_holder_name.setText(rs.getString(2));
            l_holder_balance.setText(rs.getString(11));
            l_total_amount.setText(rs.getString(11));
            l_account_type.setText(rs.getString(6).toUpperCase()+" ACCOUNT");
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_about;
    private javax.swing.JButton b_account_summary;
    private javax.swing.JButton b_accounts;
    private javax.swing.JButton b_change_password;
    private javax.swing.JButton b_funds;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton b_summary;
    private javax.swing.JButton b_update;
    private javax.swing.JButton b_update1;
    private javax.swing.JButton b_user_details;
    private javax.swing.JButton b_user_details1;
    private javax.swing.JButton b_user_details2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l_account_id;
    private javax.swing.JLabel l_account_type;
    private javax.swing.JLabel l_c_01;
    private javax.swing.JLabel l_c_02;
    private javax.swing.JLabel l_c_03;
    private javax.swing.JLabel l_c_1;
    private javax.swing.JLabel l_c_2;
    private javax.swing.JLabel l_change_password;
    private javax.swing.JLabel l_d_10;
    private javax.swing.JLabel l_d_2;
    private javax.swing.JLabel l_d_5;
    private javax.swing.JLabel l_d_6;
    private javax.swing.JLabel l_d_7;
    private javax.swing.JLabel l_d_8;
    private javax.swing.JLabel l_d_9;
    private javax.swing.JLabel l_d_birth;
    private javax.swing.JLabel l_d_contact;
    private javax.swing.JLabel l_d_email;
    private javax.swing.JLabel l_d_gender;
    private javax.swing.JLabel l_d_name;
    private javax.swing.JLabel l_f_account_id;
    private javax.swing.JLabel l_f_balance;
    private javax.swing.JLabel l_f_date;
    private javax.swing.JLabel l_f_holder_name;
    private javax.swing.JLabel l_f_transaction_id;
    private javax.swing.JLabel l_funds_heading;
    private javax.swing.JLabel l_holder_balance;
    private javax.swing.JLabel l_holder_name;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_name1;
    private javax.swing.JLabel l_name11;
    private javax.swing.JLabel l_name12;
    private javax.swing.JLabel l_total_amount;
    private javax.swing.JLabel l_u_01;
    private javax.swing.JLabel l_u_02;
    private javax.swing.JLabel l_u_1;
    private javax.swing.JLabel l_u_11;
    private javax.swing.JLabel l_u_12;
    private javax.swing.JLabel l_u_3;
    private javax.swing.JLabel l_u_4;
    private javax.swing.JLabel l_update_contact_details;
    private javax.swing.JLabel l_user_id;
    private javax.swing.JLabel lm1;
    private javax.swing.JLabel lm2;
    private javax.swing.JLabel lm3;
    private javax.swing.JLabel lm5;
    private javax.swing.JLabel lm7;
    private javax.swing.JLabel lm8;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_main_about;
    private javax.swing.JPanel p_main_account_summary;
    private javax.swing.JPanel p_main_accounts;
    private javax.swing.JPanel p_main_change_password;
    private javax.swing.JPanel p_main_details;
    private javax.swing.JPanel p_main_funds;
    private javax.swing.JPanel p_main_update;
    private javax.swing.JPanel p_side;
    private javax.swing.JPanel p_side_about;
    private javax.swing.JPanel p_side_accounts;
    private javax.swing.JPanel p_side_change_password;
    private javax.swing.JPanel p_side_funds;
    private javax.swing.JPanel p_side_update_details;
    private javax.swing.JPanel p_upper;
    private javax.swing.JTextArea ta_address;
    private javax.swing.JTextArea ta_u_address;
    private javax.swing.JTable table_account_summary;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_new_password;
    private javax.swing.JTextField tf_new_password1;
    private javax.swing.JTextField tf_old_password;
    private javax.swing.JTextField tf_u_birth;
    private javax.swing.JTextField tf_u_contact;
    private javax.swing.JTextField tf_u_email;
    private javax.swing.JTextField tf_u_gender;
    private javax.swing.JTextField tf_u_name;
    private javax.swing.JButton transfer_submit;
    // End of variables declaration//GEN-END:variables
}
